# Generated by Django 4.2.5 on 2024-01-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='Password', max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
